### PR TITLE
Fix not working when 0 is given

### PR DESCRIPTION
**Pull request by tsmsogn**

### CODE REVIEW

**Comment by dereuromark** [comment]
What about empty string?

**Comment by tsmsogn** [comment]
@dereuromark 

Thanks for suggestion. I think so too.

In addition to the test above, I'd like to add following test cases that implicitly passed in current `CakeDC:master`.
Then, I'd like to make patch and Pull Request again.
```php
		$data = array('title' => false);
		$result = $this->Article->parseCriteria($data);
		$this->assertEquals(array(), $result);

		$data = array('title' => null);
		$result = $this->Article->parseCriteria($data);
		$this->assertEquals(array(), $result);
```

**Comment by dereuromark** [comment]
false != empty string
and false will never be passed.
I would rather test with `''`

**Comment by tsmsogn** [comment]
I finally understood pointing out about test.
I modified code and made Pull Requset.

**Comment by dereuromark** [comment]
:+1:

**Comment by dereuromark** [comment]
bump

**Comment by dereuromark** [comment]
By the way, I think there is another issue regarding 0 in URLs, for me some are dropped if this patch is not applied:
https://github.com/dereuromark/search/commit/02cf82544e3f4a3dc0a5d9f9cdacfe51dbf05b8f

Can you maybe double-check @tsmsogn ?

**Comment by tsmsogn** [comment]
@dereuromark 

Okay, I will try to check about it :)

**Comment by dereuromark** [comment]
Don't wry, that was as said before for the 3.x branch only. And my fix seems to be the same thing you fixed, only for the 3.x branch.

**Comment by omnuvito** [comment]
Hi @tsmsogn, please send it to develop instead and check failing unit tests https://travis-ci.org/CakeDC/search/builds/63753326.

**Pull request closed without merging**
